import { google, sheets_v4 } from 'googleapis';
import pino from 'pino';
import { config, headers } from '../config';
import { Property, Tenant } from '../types';
import { SheetsQueue } from '../utils/sheets-queue';
import { normalizePhone } from '../utils/phone';
import { parseAmount } from '../utils/numbers';

export type PropertyFilter = { town?:string; type?:string; budgetTier?:string; apartment?:string; search?:string };
export class SheetsService {
  private api?:sheets_v4.Sheets; private readonly queue=new SheetsQueue(); private rawPropertyRowLogged=false;
  private readonly logger=pino({level:process.env.DEBUG_ROWS==='true'?'debug':config.LOG_LEVEL});
  constructor(private readonly spreadsheetId=config.GOOGLE_SHEETS_ID, api?:sheets_v4.Sheets) { this.api=api; }
  private async client(){ if(this.api)return this.api; if(!this.spreadsheetId) throw new Error('GOOGLE_SHEETS_ID is required for Sheets access'); const rawCredentials=process.env.GOOGLE_SERVICE_ACCOUNT_JSON_RAW; const auth=new google.auth.GoogleAuth({... (rawCredentials!==undefined?{credentials:JSON.parse(rawCredentials)}:{keyFile:config.GOOGLE_SERVICE_ACCOUNT_JSON}),scopes:['https://www.googleapis.com/auth/spreadsheets']}); this.api=google.sheets({version:'v4',auth}); return this.api; }
  private read<T>(tab:keyof typeof headers, map:(row:string[])=>T, onRows?:(rows:string[][])=>void, lastColumn='Z'){ return this.queue.run(async()=>{const api=await this.client();const res=await api.spreadsheets.values.get({spreadsheetId:this.spreadsheetId!,range:`${tab}!A2:${lastColumn}`});const values=(res.data.values??[]) as string[][];onRows?.(values);return values.filter(r=>r.some(Boolean)).map(r=>map(r));}); }
  private async append(tab:keyof typeof headers, values:(string|number)[], range=`${tab}!A:${String.fromCharCode(64+headers[tab].length)}`){return this.queue.run(async()=>{const api=await this.client();await api.spreadsheets.values.append({spreadsheetId:this.spreadsheetId!,range,valueInputOption:'USER_ENTERED',requestBody:{values:[values.map(v=>String(v??''))]}});});}
  private isMissingSentAlertsTab(err:unknown){const message=err instanceof Error?err.message:String(err);return /SentAlerts|sheet.*not found|unable to parse range|requested entity was not found/i.test(message);}
  async getAvailableUnits(filter:PropertyFilter, landlordId=config.LANDLORD_ID):Promise<Property[]>{const rows=await this.read('Properties',r=>({propertyId:r[0]??'',town:r[1]??'',unitName:r[2]??'',type:r[3]??'',rent:parseAmount(r[4]),deposit:parseAmount(r[5]),apartment:r[6]??'',amenities:r[7]??'',status:r[8]??'',imageUrl:r[9]??'',mapUrl:r[10]??'',budgetTier:r[11]??'',landlordId:config.LANDLORD_ID}),rawRows=>{if(!this.rawPropertyRowLogged&&(config.LOG_LEVEL==='debug'||process.env.DEBUG_ROWS==='true')){const first=rawRows.find(row=>row.some(Boolean));if(first){this.logger.debug({rawRow:first},'First raw Properties row returned by Sheets API');this.rawPropertyRowLogged=true;}}},'L');return rows.filter(p=>(p.status.toLowerCase()==='available')&&p.landlordId===landlordId&&(!filter.town||p.town.toLowerCase()===filter.town.toLowerCase())&&(!filter.type||p.type.toLowerCase().includes(filter.type.toLowerCase()))&&(!filter.budgetTier||p.budgetTier===filter.budgetTier)&&(!filter.apartment||p.apartment.toLowerCase()===filter.apartment.toLowerCase())&&(!filter.search||p.apartment.toLowerCase().includes(filter.search.toLowerCase())));}
  async getTenantByPhone(phone:string,landlordId=config.LANDLORD_ID):Promise<Tenant|undefined>{const normalizedInput=normalizePhone(phone);if(!normalizedInput)return undefined;const rows=await this.read('Tenants',r=>({tenantName:r[0]??'',firstName:r[1]??'',phoneNumber:r[2]??'',assignedUnit:r[3]??'',propertyId:r[4]??'',rentDueDate:r[5]??'',balance:parseAmount(r[6]),leaseStatus:r[7]??'',waterBill:parseAmount(r[8]),totalBill:parseAmount(r[9]),rentPaid:r[10]??'',landlordId:config.LANDLORD_ID}),undefined,'K');return rows.find(t=>t.landlordId===landlordId&&normalizePhone(t.phoneNumber)===normalizedInput);}
  async getTenants(landlordId=config.LANDLORD_ID){return this.read('Tenants',r=>({tenantName:r[0]??'',firstName:r[1]??'',phoneNumber:r[2]??'',assignedUnit:r[3]??'',propertyId:r[4]??'',rentDueDate:r[5]??'',balance:parseAmount(r[6]),leaseStatus:r[7]??'',waterBill:parseAmount(r[8]),totalBill:parseAmount(r[9]),rentPaid:r[10]??'',landlordId:config.LANDLORD_ID}),undefined,'K').then(rows=>rows.filter(t=>t.landlordId===landlordId));}
  async addPayment(t:Tenant,message:string){await this.append('Payments',[new Date().toISOString(),t.tenantName,t.phoneNumber,t.assignedUnit,'',message,'','Pending']);}
  async addMaintenance(t:Tenant,description:string){await this.append('Maintenance',[new Date().toISOString(),t.tenantName,t.assignedUnit,t.phoneNumber,'',description,'','Open']);}
  async addNotice(t:Tenant,moveOutDate:string){await this.append('Notices',[new Date().toISOString(),t.tenantName,t.phoneNumber,t.assignedUnit,moveOutDate,'Received']);}
  async addViewing(input:{name:string;phone:string;unit:string;time:string},_landlordId=config.LANDLORD_ID){await this.append('Viewings',[new Date().toISOString(),input.name,input.phone,input.unit,input.time]);}
  async addWaitlist(input:{phone:string;town:string;type:string;budget:string},_landlordId=config.LANDLORD_ID){await this.append('Waitlist',[new Date().toISOString(),input.phone,input.town,input.type,input.budget]);}
  async addSession(phone:string,flow:string,step:string,context:Record<string,unknown>,landlordId=config.LANDLORD_ID){await this.append('Sessions',[phone,flow,step,JSON.stringify(context),new Date().toISOString(),landlordId]);}
  async getLatestSession(phone:string,landlordId=config.LANDLORD_ID){const rows=await this.read('Sessions',r=>({phone:r[0]??'',flow:r[1]??'',step:r[2]??'',context:r[3]??'{}',updatedAt:r[4]??'',landlordId:r[5]??'default'}));const row=rows.filter(r=>r.phone===phone&&r.landlordId===landlordId).at(-1);if(!row||!row.flow)return undefined;try{return {...row,context:JSON.parse(row.context) as Record<string,unknown>};}catch{return undefined;}}
  async hasAlert(key:string,landlordId=config.LANDLORD_ID){try{const rows=await this.read('SentAlerts',r=>({key:r[0]??'',landlordId:r[2]??'default'}),undefined,'C');return rows.some(r=>r.key===key&&r.landlordId===landlordId);}catch(err){if(!this.isMissingSentAlertsTab(err))throw err;this.logger.error({err},'SentAlerts tab is missing; treating alert as not yet sent');return false;}}
  async markAlert(key:string,landlordId=config.LANDLORD_ID){try{await this.append('SentAlerts',[key,new Date().toISOString(),landlordId],'SentAlerts!A2:C');}catch(err){if(!this.isMissingSentAlertsTab(err))throw err;this.logger.error({err},'SentAlerts tab is missing; could not record alert delivery');}}
  async getPaymentRows(landlordId=config.LANDLORD_ID){return this.read('Payments',r=>({date:r[0]??'',tenantName:r[1]??'',phone:r[2]??'',unit:r[3]??'',amount:parseAmount(r[4]),message:r[5]??'',mpesaCode:r[6]??'',status:r[7]??'',receiptUrl:r[8]??'',duplicate:r[9]??'',landlordId:config.LANDLORD_ID}),undefined,'J').then(rows=>rows.filter(r=>r.landlordId===landlordId));}
  async setupSheets(){const api=await this.client();const meta=await api.spreadsheets.get({spreadsheetId:this.spreadsheetId!});const existing=new Set((meta.data.sheets??[]).map(s=>s.properties?.title));const requests=Object.keys(headers).filter(n=>!existing.has(n)).map(title=>({addSheet:{properties:{title}}}));if(requests.length)await api.spreadsheets.batchUpdate({spreadsheetId:this.spreadsheetId!,requestBody:{requests}});for(const [tab,cols] of Object.entries(headers))await api.spreadsheets.values.update({spreadsheetId:this.spreadsheetId!,range:`${tab}!A1`,valueInputOption:'RAW',requestBody:{values:[[...cols]]}});}
}
