import { google, sheets_v4 } from 'googleapis';
import { config, headers } from '../config';
import { Property, Tenant } from '../types';
import { SheetsQueue } from '../utils/sheets-queue';
import { digitsOnly } from '../utils/phone';

export type PropertyFilter = { town?:string; type?:string; budgetTier?:string; apartment?:string; search?:string };
export class SheetsService {
  private api?:sheets_v4.Sheets; private readonly queue=new SheetsQueue();
  constructor(private readonly spreadsheetId=config.GOOGLE_SHEETS_ID, api?:sheets_v4.Sheets) { this.api=api; }
  private async client(){ if(this.api)return this.api; if(!this.spreadsheetId) throw new Error('GOOGLE_SHEETS_ID is required for Sheets access'); const rawCredentials=process.env.GOOGLE_SERVICE_ACCOUNT_JSON_RAW; const auth=new google.auth.GoogleAuth({... (rawCredentials!==undefined?{credentials:JSON.parse(rawCredentials)}:{keyFile:config.GOOGLE_SERVICE_ACCOUNT_JSON}),scopes:['https://www.googleapis.com/auth/spreadsheets']}); this.api=google.sheets({version:'v4',auth}); return this.api; }
  private read<T>(tab:keyof typeof headers, map:(row:string[])=>T){ return this.queue.run(async()=>{const api=await this.client();const res=await api.spreadsheets.values.get({spreadsheetId:this.spreadsheetId!,range:`${tab}!A2:Z`});return (res.data.values??[]).filter(r=>r.some(Boolean)).map(r=>map(r as string[]));}); }
  private async append(tab:keyof typeof headers, values:(string|number)[]){return this.queue.run(async()=>{const api=await this.client();await api.spreadsheets.values.append({spreadsheetId:this.spreadsheetId!,range:`${tab}!A:Z`,valueInputOption:'USER_ENTERED',requestBody:{values:[values.map(v=>String(v??''))]}});});}
  async getAvailableUnits(filter:PropertyFilter, landlordId=config.LANDLORD_ID):Promise<Property[]>{const rows=await this.read('Properties',r=>({propertyId:r[0]??'',town:r[1]??'',unitName:r[2]??'',type:r[3]??'',rent:Number(r[4]??0),deposit:Number(r[5]??0),apartment:r[6]??'',amenities:r[7]??'',status:r[8]??'',imageUrl:r[9]??'',mapUrl:r[10]??'',budgetTier:r[11]??'',landlordId:r[12]??'default'}));return rows.filter(p=>(p.status.toLowerCase()==='available')&&p.landlordId===landlordId&&(!filter.town||p.town.toLowerCase()===filter.town.toLowerCase())&&(!filter.type||p.type.toLowerCase().includes(filter.type.toLowerCase()))&&(!filter.budgetTier||p.budgetTier===filter.budgetTier)&&(!filter.apartment||p.apartment.toLowerCase()===filter.apartment.toLowerCase())&&(!filter.search||p.apartment.toLowerCase().includes(filter.search.toLowerCase())));}
  async getTenantByPhone(phone:string,landlordId=config.LANDLORD_ID):Promise<Tenant|undefined>{const rows=await this.read('Tenants',r=>({tenantName:r[0]??'',firstName:r[1]??'',phoneNumber:r[2]??'',assignedUnit:r[3]??'',propertyId:r[4]??'',rentDueDate:r[5]??'',balance:Number(r[6]??0),leaseStatus:r[7]??'',waterBill:Number(r[8]??0),totalBill:Number(r[9]??0),rentPaid:r[10]??'',landlordId:r[11]??'default'}));return rows.find(t=>t.landlordId===landlordId&&digitsOnly(t.phoneNumber).endsWith(digitsOnly(phone)));}
  async getTenants(landlordId=config.LANDLORD_ID){return this.read('Tenants',r=>({tenantName:r[0]??'',firstName:r[1]??'',phoneNumber:r[2]??'',assignedUnit:r[3]??'',propertyId:r[4]??'',rentDueDate:r[5]??'',balance:Number(r[6]??0),leaseStatus:r[7]??'',waterBill:Number(r[8]??0),totalBill:Number(r[9]??0),rentPaid:r[10]??'',landlordId:r[11]??'default'})).then(rows=>rows.filter(t=>t.landlordId===landlordId));}
  async addPayment(t:Tenant,message:string){await this.append('Payments',[new Date().toISOString(),t.tenantName,t.phoneNumber,t.assignedUnit,message,'Pending','No',t.propertyId,t.landlordId]);}
  async addMaintenance(t:Tenant,description:string){await this.append('Maintenance',[new Date().toISOString(),t.tenantName,t.assignedUnit,t.phoneNumber,description,'Open',t.propertyId,t.landlordId]);}
  async addNotice(t:Tenant,moveOutDate:string){await this.append('Notices',[new Date().toISOString(),t.tenantName,t.phoneNumber,t.assignedUnit,moveOutDate,'Received',t.propertyId,t.landlordId]);}
  async addViewing(input:{name:string;phone:string;unit:string;time:string},landlordId=config.LANDLORD_ID){await this.append('Viewings',[new Date().toISOString(),input.name,input.phone,input.unit,input.time,landlordId]);}
  async addWaitlist(input:{phone:string;town:string;type:string;budget:string},landlordId=config.LANDLORD_ID){await this.append('Waitlist',[new Date().toISOString(),input.phone,input.town,input.type,input.budget,landlordId]);}
  async addSession(phone:string,flow:string,step:string,context:Record<string,unknown>,landlordId=config.LANDLORD_ID){await this.append('Sessions',[phone,flow,step,JSON.stringify(context),new Date().toISOString(),landlordId]);}
  async getLatestSession(phone:string,landlordId=config.LANDLORD_ID){const rows=await this.read('Sessions',r=>({phone:r[0]??'',flow:r[1]??'',step:r[2]??'',context:r[3]??'{}',updatedAt:r[4]??'',landlordId:r[5]??'default'}));const row=rows.filter(r=>r.phone===phone&&r.landlordId===landlordId).at(-1);if(!row||!row.flow)return undefined;try{return {...row,context:JSON.parse(row.context) as Record<string,unknown>};}catch{return undefined;}}
  async hasAlert(key:string,landlordId=config.LANDLORD_ID){const rows=await this.read('SentAlerts',r=>({key:r[0]??'',landlordId:r[2]??'default'}));return rows.some(r=>r.key===key&&r.landlordId===landlordId);}
  async markAlert(key:string,landlordId=config.LANDLORD_ID){await this.append('SentAlerts',[key,new Date().toISOString(),landlordId]);}
  async getPaymentRows(landlordId=config.LANDLORD_ID){return this.read('Payments',r=>({date:r[0]??'',tenantName:r[1]??'',phone:r[2]??'',unit:r[3]??'',message:r[4]??'',status:r[5]??'',receiptSent:r[6]??'',propertyId:r[7]??'',landlordId:r[8]??'default'})).then(rows=>rows.filter(r=>r.landlordId===landlordId));}
  async markReceiptSent(rowIndex:number){const api=await this.client();await api.spreadsheets.values.update({spreadsheetId:this.spreadsheetId!,range:`Payments!G${rowIndex}`,valueInputOption:'USER_ENTERED',requestBody:{values:[['Yes']]}});}
  async setupSheets(){const api=await this.client();const meta=await api.spreadsheets.get({spreadsheetId:this.spreadsheetId!});const existing=new Set((meta.data.sheets??[]).map(s=>s.properties?.title));const requests=Object.keys(headers).filter(n=>!existing.has(n)).map(title=>({addSheet:{properties:{title}}}));if(requests.length)await api.spreadsheets.batchUpdate({spreadsheetId:this.spreadsheetId!,requestBody:{requests}});for(const [tab,cols] of Object.entries(headers))await api.spreadsheets.values.update({spreadsheetId:this.spreadsheetId!,range:`${tab}!A1`,valueInputOption:'RAW',requestBody:{values:[[...cols]]}});}
}
