import {describe,it,expect,vi} from 'vitest';
import {FlowEngine} from './flow-engine';
import {MemorySessionStore} from './services/session.service';
import {config} from './config';
import {BODY_LIMIT} from './utils/whatsapp-ui';

function setup(){
 const sent:string[]=[];const wa:any={sendText:vi.fn(async(_to:string,text:string)=>{sent.push(text)}),sendButtons:vi.fn(async(_to:string,text:string)=>{sent.push(text)}),sendList:vi.fn(async()=>{}),sendImage:vi.fn(async()=>{})};
 const sheets:any={addSession:vi.fn(async()=>{}),addViewing:vi.fn(async()=>{}),addWaitlist:vi.fn(async()=>{}),getAvailableUnits:vi.fn(async()=>[]),getTenantByPhone:vi.fn(async()=>undefined),getViewings:vi.fn(async()=>[]),getTenants:vi.fn(async()=>[]),getPaymentRows:vi.fn(async()=>[]),getOccupancy:vi.fn(async()=>({occupied:0,total:0})),hasAlert:vi.fn(async()=>false),markAlert:vi.fn(async()=>{}),setPaymentStatus:vi.fn(async()=>{})};
 const alerts={send:vi.fn(async()=>{})};
 const sessions=new MemorySessionStore();
 return {engine:new FlowEngine(wa,sheets,sessions,alerts as any),wa,sheets,sessions,sent};
}
describe('conversation entry flows',()=>{
 it('shows customer menu for a new conversation',async()=>{const {engine,wa}=setup();await engine.handle({phone:'+254712345678',text:'hello'});expect(wa.sendButtons).toHaveBeenCalled();});
 it('shows the landlord dashboard for landlord hi and not for a client phone',async()=>{const {engine,wa}=setup();await engine.handle({phone:config.LANDLORD_PHONE,text:'hi'});expect(wa.sendButtons).toHaveBeenCalledTimes(2);expect(wa.sendButtons.mock.calls[0]?.[2]).toEqual([{id:'landlord-viewings',title:"Today's viewings"},{id:'landlord-overdue',title:'Overdue tenants'},{id:'landlord-stats',title:'Stats'}]);const client=setup();await client.engine.handle({phone:'+254712345678',text:'hi'});expect(client.wa.sendButtons).toHaveBeenCalledTimes(1);expect(client.wa.sendButtons.mock.calls[0]?.[1]).toContain('Welcome to');});
 it('chunks a long landlord overdue report and leaves a short dashboard button',async()=>{const {engine,wa,sheets}=setup();sheets.getTenants=vi.fn(async()=>Array.from({length:50},(_,index)=>({tenantName:`Tenant ${index+1}`,assignedUnit:`Apartment Unit ${index+1}`,rentPaid:'No',totalBill:100000-index})));await engine.handle({phone:config.LANDLORD_PHONE,text:'overdue'});expect(wa.sendText).toHaveBeenCalled();expect(wa.sendText.mock.calls.every(([,body]:[string,string])=>body.length<=BODY_LIMIT)).toBe(true);expect(wa.sendButtons).toHaveBeenCalledOnce();const [,_body,buttons]=wa.sendButtons.mock.calls[0] as [string,string,{id:string;title:string}[]];expect(_body.length).toBeLessThanOrEqual(BODY_LIMIT);expect(buttons).toEqual([{id:'landlord-menu',title:'Back to dashboard'}]);expect(wa.sendText.mock.invocationCallOrder.at(-1)).toBeLessThan(wa.sendButtons.mock.invocationCallOrder[0]!);});
 it('verifies a matching payment and sends its receipt only once',async()=>{const {engine,wa,sheets}=setup();const payment:any={rowNumber:7,date:'2026-10-06',tenantName:'Ada Tenant',phone:'+254712345678',unit:'Unit 1A',amount:25000,message:'ABC123 confirmation',mpesaCode:'',status:'Pending',receiptUrl:'',duplicate:'',landlordId:config.LANDLORD_ID};sheets.getPaymentRows=vi.fn(async()=>[payment]);sheets.setPaymentStatus=vi.fn(async(_row:number,status:string)=>{payment.status=status;});await engine.handle({phone:config.LANDLORD_PHONE,text:'verify ABC123'});await engine.handle({phone:config.LANDLORD_PHONE,text:'verify ABC123'});expect(sheets.setPaymentStatus).toHaveBeenCalledOnce();expect(payment.status).toBe('Verified');expect(wa.sendText).toHaveBeenCalledTimes(1);expect(wa.sendText.mock.calls[0]?.[1]).toContain('Payment receipt');});
 it('confirms a viewing with its unit, time, and next-step buttons',async()=>{const {engine,wa,sessions}=setup();const phone='+254712345678';await sessions.set({phone,flow:'viewing',step:'time',context:{name:'Ada',phone:'+254712345678',unit:'Unit 1A'},updatedAt:'',landlordId:'default'});await engine.handle({phone,text:'Saturday at 2pm'});expect(wa.sendButtons).toHaveBeenCalledWith(phone,expect.stringContaining('*Viewing requested*'),[{id:'book-another',title:'Book another'},{id:'main-menu',title:'Main Menu'}]);expect(wa.sendButtons.mock.calls.at(-1)?.[1]).toContain('Unit 1A');expect(wa.sendButtons.mock.calls.at(-1)?.[1]).toContain('Saturday at 2pm');});
 it('captures a waitlist name and confirms the complete request with navigation',async()=>{const {engine,wa,sheets,sessions}=setup();const phone='+254712345678';await sessions.set({phone,flow:'waitlist',step:'consent',context:{town:'Nairobi',type:'Bedsitter',budget:'15000'},updatedAt:'',landlordId:'default'});await engine.handle({phone,text:'yes'});await engine.handle({phone,text:'Ada'});await engine.handle({phone,text:'0712345678'});expect(sheets.addWaitlist).toHaveBeenCalledWith({name:'Ada',phone:'+254712345678',town:'Nairobi',type:'Bedsitter',budget:'15000'});expect(wa.sendButtons.mock.calls.at(-1)?.[1]).toContain('*You\'re on the waitlist*');expect(wa.sendButtons.mock.calls.at(-1)?.[2]).toEqual([{id:'browse-now',title:'Browse now'},{id:'main-menu',title:'Main Menu'}]);});
 it('starts quick search from the menu selection',async()=>{const {engine,wa}=setup();await engine.handle({phone:'+254712345678',text:'quick',kind:'button'});expect(wa.sendText).toHaveBeenCalledWith('+254712345678',expect.stringContaining('apartment name'));});
 it.each(['Tenant','tenant'])('starts tenant verification for %s',async keyword=>{const {engine,wa,sessions}=setup();await engine.handle({phone:'+254712345678',text:keyword});expect(wa.sendText).toHaveBeenCalledWith('+254712345678',expect.stringContaining('registered phone number'));expect((await sessions.get('+254712345678'))?.flow).toBe('tenantVerify');});
 it('offers recovery when tenant lookup fails',async()=>{const {engine,wa}=setup();await engine.handle({phone:'+254712345678',text:'tenant'});await engine.handle({phone:'+254712345678',text:'123456789'});expect(wa.sendButtons).toHaveBeenCalledWith('+254712345678','Account not found.',expect.arrayContaining([expect.objectContaining({id:'retry'})]));});
 it('uses unique compact buttons for three or fewer units',async()=>{const {engine,wa,sheets,sessions}=setup();const phone='+254712345678';const units=[1,2,3].map(n=>({unitName:`Sunset Ridge Apartments - Unit ${n}B`,apartment:'Sunset Ridge Apartments',rent:25000,type:'2 Bed Apartment'}));sheets.getAvailableUnits=vi.fn(async()=>units);await sessions.set({phone,flow:'browse',step:'apartment',context:{town:'Kitengela',type:'2 Bed Apartment',budgetTier:'25k+'},updatedAt:'',landlordId:'default'});await engine.handle({phone,text:'Sunset Ridge Apartments'});expect(wa.sendButtons).toHaveBeenCalledWith(phone,'Choose a unit:',[{id:units[0]!.unitName,title:'Unit 1B'},{id:units[1]!.unitName,title:'Unit 2B'},{id:units[2]!.unitName,title:'Unit 3B'}]);});
 it('uses a unit list for more than three units and preserves full unit IDs',async()=>{const {engine,wa,sheets,sessions}=setup();const phone='+254712345678';const units=Array.from({length:4},(_,index)=>({unitName:`Sunset Ridge Apartments - Unit ${index+1}B`,apartment:'Sunset Ridge Apartments',rent:25000,type:'2 Bed Apartment'}));sheets.getAvailableUnits=vi.fn(async()=>units);await sessions.set({phone,flow:'browse',step:'apartment',context:{town:'Kitengela',type:'2 Bed Apartment',budgetTier:'25k+'},updatedAt:'',landlordId:'default'});await engine.handle({phone,text:'Sunset Ridge Apartments'});expect(wa.sendList).toHaveBeenCalledWith(phone,'Choose a unit:',[{title:'Sunset Ridge Apartments',rows:units.map((unit,index)=>({id:unit.unitName,title:`Unit ${index+1}B`,description:'KES 25,000 · 2 Bed Apartment'}))}],'Choose Unit');expect(wa.sendButtons).not.toHaveBeenCalled();});
 it('uses an apartment list for more than three apartments',async()=>{const {engine,wa,sheets,sessions}=setup();const phone='+254712345678';const names=['Sunset Ridge Apartments','Sunset Ridge Apartments Phase 2','Hope Gardens','Liberty Court'];sheets.getAvailableUnits=vi.fn(async()=>names.map(apartment=>({apartment})));await sessions.set({phone,flow:'browse',step:'budget',context:{town:'Kitengela',type:'2 Bed Apartment'},updatedAt:'',landlordId:'default'});await engine.handle({phone,text:'25k+'});expect(wa.sendList).toHaveBeenCalledWith(phone,'Available apartments:',[{title:'Apartments',rows:[{id:names[0],title:'Sunset Ridge'},{id:names[1],title:'Sunset Ridge (2)'},{id:names[2],title:'Hope Gardens'},{id:names[3],title:'Liberty Court'}]}],'Choose Apartment');});
});
