import {describe,it,expect,vi} from 'vitest';
import {FlowEngine} from './flow-engine';
import {MemorySessionStore} from './services/session.service';

function setup(){
 const sent:string[]=[];const wa:any={sendText:vi.fn(async(_to:string,text:string)=>{sent.push(text)}),sendButtons:vi.fn(async(_to:string,text:string)=>{sent.push(text)}),sendList:vi.fn(async()=>{}),sendImage:vi.fn(async()=>{})};
 const sheets:any={addSession:vi.fn(async()=>{}),getAvailableUnits:vi.fn(async()=>[]),getTenantByPhone:vi.fn(async()=>undefined)};
 const alerts={send:vi.fn(async()=>{})};
 const sessions=new MemorySessionStore();
 return {engine:new FlowEngine(wa,sheets,sessions,alerts as any),wa,sheets,sessions,sent};
}
describe('conversation entry flows',()=>{
 it('shows customer menu for a new conversation',async()=>{const {engine,wa}=setup();await engine.handle({phone:'+254712345678',text:'hello'});expect(wa.sendButtons).toHaveBeenCalled();});
 it('starts quick search from the menu selection',async()=>{const {engine,wa}=setup();await engine.handle({phone:'+254712345678',text:'quick',kind:'button'});expect(wa.sendText).toHaveBeenCalledWith('+254712345678',expect.stringContaining('apartment name'));});
 it('starts tenant verification on tenant keyword',async()=>{const {engine,wa}=setup();await engine.handle({phone:'+254712345678',text:'tenant'});expect(wa.sendText).toHaveBeenCalledWith('+254712345678',expect.stringContaining('last 9 digits'));});
 it('offers recovery when tenant lookup fails',async()=>{const {engine,wa}=setup();await engine.handle({phone:'+254712345678',text:'tenant'});await engine.handle({phone:'+254712345678',text:'123456789'});expect(wa.sendButtons).toHaveBeenCalledWith('+254712345678','Account not found.',expect.arrayContaining([expect.objectContaining({id:'retry'})]));});
 it('uses unique compact buttons for three or fewer units',async()=>{const {engine,wa,sheets,sessions}=setup();const phone='+254712345678';const units=[1,2,3].map(n=>({unitName:`Sunset Ridge Apartments - Unit ${n}B`,apartment:'Sunset Ridge Apartments',rent:25000,type:'2 Bed Apartment'}));sheets.getAvailableUnits=vi.fn(async()=>units);await sessions.set({phone,flow:'browse',step:'apartment',context:{town:'Kitengela',type:'2 Bed Apartment',budgetTier:'25k+'},updatedAt:'',landlordId:'default'});await engine.handle({phone,text:'Sunset Ridge Apartments'});expect(wa.sendButtons).toHaveBeenCalledWith(phone,'Choose a unit:',[{id:units[0]!.unitName,title:'Unit 1B'},{id:units[1]!.unitName,title:'Unit 2B'},{id:units[2]!.unitName,title:'Unit 3B'}]);});
 it('uses a unit list for more than three units and preserves full unit IDs',async()=>{const {engine,wa,sheets,sessions}=setup();const phone='+254712345678';const units=Array.from({length:4},(_,index)=>({unitName:`Sunset Ridge Apartments - Unit ${index+1}B`,apartment:'Sunset Ridge Apartments',rent:25000,type:'2 Bed Apartment'}));sheets.getAvailableUnits=vi.fn(async()=>units);await sessions.set({phone,flow:'browse',step:'apartment',context:{town:'Kitengela',type:'2 Bed Apartment',budgetTier:'25k+'},updatedAt:'',landlordId:'default'});await engine.handle({phone,text:'Sunset Ridge Apartments'});expect(wa.sendList).toHaveBeenCalledWith(phone,'Choose a unit:',[{title:'Sunset Ridge Apartments',rows:units.map((unit,index)=>({id:unit.unitName,title:`Unit ${index+1}B`,description:'KES 25,000 · 2 Bed Apartment'}))}],'Choose Unit');expect(wa.sendButtons).not.toHaveBeenCalled();});
 it('uses an apartment list for more than three apartments',async()=>{const {engine,wa,sheets,sessions}=setup();const phone='+254712345678';const names=['Sunset Ridge Apartments','Sunset Ridge Apartments Phase 2','Hope Gardens','Liberty Court'];sheets.getAvailableUnits=vi.fn(async()=>names.map(apartment=>({apartment})));await sessions.set({phone,flow:'browse',step:'budget',context:{town:'Kitengela',type:'2 Bed Apartment'},updatedAt:'',landlordId:'default'});await engine.handle({phone,text:'25k+'});expect(wa.sendList).toHaveBeenCalledWith(phone,'Available apartments:',[{title:'Apartments',rows:[{id:names[0],title:'Sunset Ridge'},{id:names[1],title:'Sunset Ridge (2)'},{id:names[2],title:'Hope Gardens'},{id:names[3],title:'Liberty Court'}]}],'Choose Apartment');});
});
